/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LabRouteImport } from './routes/lab'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as HistoryAnalysisIdRouteImport } from './routes/history.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryAnalysisIdRoute = HistoryAnalysisIdRouteImport.update({
  id: '/$analysisId',
  path: '/$analysisId',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/history': typeof HistoryRouteWithChildren
  '/lab': typeof LabRoute
  '/paper': typeof PaperRoute
  '/scanner': typeof ScannerRoute
  '/tournament': typeof TournamentRoute
  '/history/$analysisId': typeof HistoryAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/history': typeof HistoryRouteWithChildren
  '/lab': typeof LabRoute
  '/paper': typeof PaperRoute
  '/scanner': typeof ScannerRoute
  '/tournament': typeof TournamentRoute
  '/history/$analysisId': typeof HistoryAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/history': typeof HistoryRouteWithChildren
  '/lab': typeof LabRoute
  '/paper': typeof PaperRoute
  '/scanner': typeof ScannerRoute
  '/tournament': typeof TournamentRoute
  '/history/$analysisId': typeof HistoryAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/history'
    | '/lab'
    | '/paper'
    | '/scanner'
    | '/tournament'
    | '/history/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/history'
    | '/lab'
    | '/paper'
    | '/scanner'
    | '/tournament'
    | '/history/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/history'
    | '/lab'
    | '/paper'
    | '/scanner'
    | '/tournament'
    | '/history/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LabRoute: typeof LabRoute
  PaperRoute: typeof PaperRoute
  ScannerRoute: typeof ScannerRoute
  TournamentRoute: typeof TournamentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$analysisId': {
      id: '/history/$analysisId'
      path: '/$analysisId'
      fullPath: '/history/$analysisId'
      preLoaderRoute: typeof HistoryAnalysisIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryAnalysisIdRoute: typeof HistoryAnalysisIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryAnalysisIdRoute: HistoryAnalysisIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LabRoute: LabRoute,
  PaperRoute: PaperRoute,
  ScannerRoute: ScannerRoute,
  TournamentRoute: TournamentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
